In [26]:
import numpy


**Array Creation: Conversion from other Python structures**


In [27]:
listarray = numpy.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
listarray


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
listarray.dtype


dtype('int32')

In [29]:
listarray.shape


(3, 3)

In [30]:
listarray.size

9

*zeros will create an array of given dimension*

In [31]:
zeros = numpy.zeros((2,5))
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

*arange is just like python range function*

In [32]:
rng = numpy.arange(15)
print(rng)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


*linspace creates numbers equally spaced in between two given numbers*

In [33]:

lspace = numpy.linspace(1, 10, 8)
lspace2 = numpy.linspace(1, 10, 9)
lspace3 = numpy.linspace(1, 10, 10)
print(lspace)
print(lspace2)
lspace3

[ 1.          2.28571429  3.57142857  4.85714286  6.14285714  7.42857143
  8.71428571 10.        ]
[ 1.     2.125  3.25   4.375  5.5    6.625  7.75   8.875 10.   ]


array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

*generate random numbers array*

In [38]:
emp = numpy.empty((4,6))


In [39]:
emp

array([[1.33135947e-311, 7.60861095e-322, 0.00000000e+000,
        0.00000000e+000, 1.11261027e-306, 1.16095484e-028],
       [9.31115457e+242, 4.52341894e+257, 2.59345444e+161,
        2.99938059e-067, 1.72854786e-056, 5.47033815e-095],
       [1.05234357e-153, 6.80081107e+199, 2.95162258e+137,
        1.96100257e+243, 4.27255707e+180, 9.31115457e+242],
       [2.16209973e+233, 2.87520342e+161, 4.61968666e+281,
        6.32672800e+180, 4.74483502e+170, 4.59210323e-072]])

In [40]:
emp_like = numpy.empty_like(lspace)

In [41]:
emp_like

array([ 1.        ,  2.28571429,  3.57142857,  4.85714286,  6.14285714,
        7.42857143,  8.71428571, 10.        ])

In [42]:
ide = numpy.identity(45)

In [43]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [44]:
arr = numpy.arange(99)

In [45]:
arr.reshape(3, 33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [46]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [52]:
ar = numpy.array([[1, 2, 3], [4, 5, 6], [7, 1, 0]])

In [54]:
ar.sum(axis = 0)

array([12,  8,  9])

In [55]:
ar.sum(axis = 1)

array([ 6, 15,  8])

*transpose*

In [56]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [57]:
ar.flat

In [58]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


*number of dimensions*

In [59]:
ar.ndim

2

In [60]:
one = numpy.array([1, 66, 42, 76])

In [61]:
one.argmax()

3